// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using BddSharp.Kernel;
namespace BddTest
{
    /// <summary>
    ///This is a test class for BddSharp.Kernel.FddKernel and is intended
    ///to contain all BddSharp.Kernel.FddKernel Unit Tests
    ///</summary>
    [TestClass()]
    public class FddKernelTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        [TestInitialize()]
        public void MyTestInitialize()
        {
            FddKernel.Setup();
        }
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for AnySat (Bdd, int)
        ///</summary>
        [TestMethod()]
        public void AnySatTest()
        {
            Fdd u1 = new Fdd(3);
            Fdd u2 = new Fdd(5);

            
            Bdd actual;

            actual = BddSharp.Kernel.FddKernel.Xor(u1, u2);
            int[] i = FddKernel.AnySat(actual, 3);

            Assert.AreEqual(2, i.Length, "Both u1,u2 returned a valid answers in AnySat.");
        }

        /// <summary>
        ///A test for Xor (Fdd, Fdd)
        ///</summary>
        [TestMethod()]
        public void XorTest()
        {
            Fdd u1 = new Fdd(3);
            Fdd u2 = new Fdd(5);

            
            Bdd actual;

            actual = BddSharp.Kernel.FddKernel.Xor(u1, u2);
            int[] i = FddKernel.AnySat(actual, 3);
            
            Assert.AreNotEqual(i[0],i[1], "After an xor each factor must differ, but does not");
        }

    }


}
