// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using BddSharp.Parser;
using System.IO;
namespace ParserTest
{
    /// <summary>
    ///This is a test class for BddSharp.Parser.Scanner and is intended
    ///to contain all BddSharp.Parser.Scanner Unit Tests
    ///</summary>
    [TestClass()]
    public class ScannerTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Scan (TextReader)
        ///</summary>
        [TestMethod()]
        public void ScanTest()
        {
            Scanner target = new Scanner();

            TextReader reader = null; // TODO: Initialize to an appropriate value

            System.Collections.Generic.IEnumerator<BddSharp.Parser.Token> expected = null;
            System.Collections.Generic.IEnumerator<BddSharp.Parser.Token> actual;

            actual = target.Scan(reader);

            Assert.AreEqual(expected, actual, "BddSharp.Parser.Scanner.Scan did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
