// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using BddSharp.AST;
using BddSharp.Parser;
namespace ParserTest
{
    /// <summary>
    ///This is a test class for BddSharp.Parser.Token and is intended
    ///to contain all BddSharp.Parser.Token Unit Tests
    ///</summary>
    [TestClass()]
    public class TokenTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for FromKind (Kind)
        ///</summary>
        [TestMethod()]
        public void FromKindTest()
        {
            Kind k = Kind.EOF; // TODO: Initialize to an appropriate value

            Token expected = new Token();
            Token actual;

            actual = BddSharp.Parser.Token.FromKind(k);

            Assert.AreEqual(expected, actual, "BddSharp.Parser.Token.FromKind did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for FromString (string)
        ///</summary>
        [TestMethod()]
        public void FromStringTest()
        {
            string s = null; // TODO: Initialize to an appropriate value

            Token expected = new Token();
            Token actual;

            actual = BddSharp.Parser.Token.FromString(s);

            Assert.AreEqual(expected, actual, "BddSharp.Parser.Token.FromString did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for Token (char)
        ///</summary>
        [TestMethod()]
        public void ConstructorTest()
        {
            Token target = new Token(Kind.VAR);

        //    // TODO: Implement code to verify target
        //    Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for Token (Kind)
        ///</summary>
        [TestMethod()]
        public void ConstructorTest1()
        {
            Kind k = Kind.EOF; // TODO: Initialize to an appropriate value

            Token target = new Token(k);

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for Token (string)
        ///</summary>
        [TestMethod()]
        public void ConstructorTest2()
        {
            string s = null; // TODO: Initialize to an appropriate value

            Token target = new Token(s);

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

    }


}
